# Generated by Django 4.0.4 on 2022-05-02 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0003_memberentry_address1_memberentry_address2_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='memberentry',
            old_name='zip',
            new_name='zip_code',
        ),
        migrations.AlterField(
            model_name='memberentry',
            name='address2',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='memberentry',
            name='allergies',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='memberentry',
            name='class_year',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='memberentry',
            name='injuries',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='memberentry',
            name='school',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
