# Generated by Django 4.0.4 on 2022-05-02 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0004_rename_zip_memberentry_zip_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memberentry',
            name='address2',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='memberentry',
            name='allergies',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='memberentry',
            name='class_year',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='memberentry',
            name='injuries',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='memberentry',
            name='school',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
